#!/bin/bash
# Plan Review Hook - Headless subagent analysis
# Invokes specialized agents to review plan before implementation
# Can be called manually or by pre-implementation hook

set -e

PLANS_DIR="${CLAUDE_WORKING_DIRECTORY:-$(pwd)}/.agent/Plans"
REVIEWS_DIR="$PLANS_DIR/reviews"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

# Find active plan files
PLAN_FILES=$(find "$PLANS_DIR" -maxdepth 1 -name "*.md" -type f 2>/dev/null || echo "")

if [ -z "$PLAN_FILES" ]; then
    echo "INFO: No active plan files found for review"
    exit 0
fi

mkdir -p "$REVIEWS_DIR"

# Process each plan
for plan_file in $PLAN_FILES; do
    if [ -f "$plan_file" ]; then
        filename=$(basename "$plan_file" .md)
        plan_content=$(cat "$plan_file")

        echo ""
        echo "PLAN REVIEW: $filename"
        echo "=============================================="

        # Check if Claude CLI is available for headless execution
        if command -v claude &> /dev/null; then
            echo "Running headless review with Claude CLI..."

            # Architecture Review (arch-validator)
            ARCH_REVIEW=$(claude --print -p "You are an architecture validator. Review this plan for:
1. Nx library structure compliance (scope/type tags)
2. Dependency matrix violations
3. Facade pattern usage
4. Import patterns (direct vs barrel)

Plan:
$plan_content

Provide ONLY critical issues in bullet points. If no issues, say 'ARCHITECTURE: OK'" 2>/dev/null || echo "ARCHITECTURE: Review skipped (CLI unavailable)")

            # Code Quality Review (code-reviewer)
            CODE_REVIEW=$(claude --print -p "You are a code quality reviewer. Check this plan for:
1. Single Responsibility violations
2. Component complexity risks
3. Missing test considerations
4. Potential security issues

Plan:
$plan_content

Provide ONLY critical issues in bullet points. If no issues, say 'CODE QUALITY: OK'" 2>/dev/null || echo "CODE QUALITY: Review skipped (CLI unavailable)")

            # Save review
            REVIEW_FILE="$REVIEWS_DIR/${filename}_review_${TIMESTAMP}.md"
            cat > "$REVIEW_FILE" << EOF
# Plan Review: $filename
**Date:** $(date +"%Y-%m-%d %H:%M:%S")
**Plan File:** $plan_file

## Architecture Review
$ARCH_REVIEW

## Code Quality Review
$CODE_REVIEW

---
*Generated by plan-review.sh headless analysis*
EOF

            echo "Review saved: $REVIEW_FILE"
            echo ""
            echo "Architecture: $(echo "$ARCH_REVIEW" | head -1)"
            echo "Code Quality: $(echo "$CODE_REVIEW" | head -1)"

        else
            # Fallback: Static analysis without Claude CLI
            echo "Claude CLI not available. Running static checks..."

            ISSUES=""

            # Check for common patterns in plan
            if echo "$plan_content" | grep -qi "barrel\|index.ts"; then
                ISSUES="$ISSUES\n- WARNING: Plan mentions barrel imports. Prefer direct imports."
            fi

            if ! echo "$plan_content" | grep -qi "facade\|service"; then
                ISSUES="$ISSUES\n- NOTICE: No facade mentioned. Ensure state management follows Facade Pattern."
            fi

            if ! echo "$plan_content" | grep -qi "test\|spec"; then
                ISSUES="$ISSUES\n- WARNING: No test strategy mentioned in plan."
            fi

            if echo "$plan_content" | grep -qiE "feature.*import.*domain|component.*import.*data-source"; then
                ISSUES="$ISSUES\n- CRITICAL: Potential dependency matrix violation detected."
            fi

            if [ -n "$ISSUES" ]; then
                echo -e "Static Analysis Issues:$ISSUES"
            else
                echo "Static Analysis: No obvious issues detected."
            fi
        fi

        echo "=============================================="
    fi
done

echo ""
echo "<system-reminder>"
echo "PLAN REVIEW COMPLETED"
echo ""
echo "Before implementing, ensure:"
echo "1. All critical issues are addressed"
echo "2. Architecture rules are followed (.agent/System/)"
echo "3. Dependency matrix is respected"
echo "4. Tests are planned for new code"
echo ""
echo "Review files saved in: .agent/Plans/reviews/"
echo "</system-reminder>"

exit 0
